### ISSUE TITLE
Crashing with iOS 9

### ISSUE THREAD

**Issue by shutterflypro** [sandeepmistry/AnyiBeacon-iOS#1]
Any ideas why this no longer works on iOS 9??

**Comment by sandeepmistry** [comment]
@shutterflypro the internal structure has been changed in iOS 9, I've updated based on the run time headers: https://github.com/sandeepmistry/AnyiBeacon-iOS/commit/3e9946c24e5eb34b73e7544d30bc742a62c211b7 and made iOS 9 the minimum.

Bonus: there is also a UI included now
